DROP TABLE IF EXISTS products CASCADE;
create table products (
	product_id INT,
	product_name VARCHAR(50),
	active BOOLEAN
);
insert into products (product_id, product_name, active) values (1, 'Subin Crisped Goldenbush', false);
insert into products (product_id, product_name, active) values (2, 'Span Island Goldback Fern', false);
insert into products (product_id, product_name, active) values (3, 'Y-find Prickly Gousblom', true);
insert into products (product_id, product_name, active) values (4, 'Hatity Wailua River Yellow Loosestrife', false);
insert into products (product_id, product_name, active) values (5, 'Cardify Cooper''s Lipfern', false);
insert into products (product_id, product_name, active) values (6, 'Bitchip Fanmustard', true);
insert into products (product_id, product_name, active) values (7, 'Tempsoft Rimmed Lichen', true);
insert into products (product_id, product_name, active) values (8, 'Zontrax Columbia Needlegrass', true);
insert into products (product_id, product_name, active) values (9, 'Holdlamis Rigid Didymodon Moss', true);
insert into products (product_id, product_name, active) values (10, 'Asoka Giant-trumpets', false);
insert into products (product_id, product_name, active) values (11, 'Job Monkey Fingers', true);
insert into products (product_id, product_name, active) values (12, 'Asoka Mountain Dodder', false);
insert into products (product_id, product_name, active) values (13, 'Job Cathedral Bluff Dwarf Gentian', true);
insert into products (product_id, product_name, active) values (14, 'Biodex Waianae Range Alsinidendron', true);
insert into products (product_id, product_name, active) values (15, 'Wrapsafe Pondweed', false);
insert into products (product_id, product_name, active) values (16, 'Regrant Chee Reedgrass', true);
insert into products (product_id, product_name, active) values (17, 'Zamit Crabgrass', false);
insert into products (product_id, product_name, active) values (18, 'Cardguard Frogwood', true);
insert into products (product_id, product_name, active) values (19, 'Rank Island Broom', true);
insert into products (product_id, product_name, active) values (20, 'Ventosanzap Isothecium Moss', true);
insert into products (product_id, product_name, active) values (21, 'Stronghold Oakwoods Prairie Clover', true);
insert into products (product_id, product_name, active) values (22, 'Prodder Entireleaf Yellow False Foxglove', true);
insert into products (product_id, product_name, active) values (23, 'Domainer Dogwood', true);
insert into products (product_id, product_name, active) values (24, 'Voyatouch Oahu Flatsedge', true);
insert into products (product_id, product_name, active) values (25, 'Trippledex Mojave Spikemoss', false);
insert into products (product_id, product_name, active) values (26, 'Holdlamis Newberry''s Milkvetch', false);
insert into products (product_id, product_name, active) values (27, 'Holdlamis Beard Lichen', false);
insert into products (product_id, product_name, active) values (28, 'Tres-Zap Swamp Onion', true);
insert into products (product_id, product_name, active) values (29, 'Tres-Zap Glandleaf Prairie Clover', true);
insert into products (product_id, product_name, active) values (30, 'Toughjoyfax Socrates Mine Jewelflower', false);
insert into products (product_id, product_name, active) values (31, 'Gembucket Bayrumtree', false);
insert into products (product_id, product_name, active) values (32, 'It Annual Nehe', false);
insert into products (product_id, product_name, active) values (33, 'Domainer Lemmon''s Brickellbush', false);
insert into products (product_id, product_name, active) values (34, 'Opela Wild Oilnut', false);
insert into products (product_id, product_name, active) values (35, 'Bitwolf Southern Lobelia', true);
insert into products (product_id, product_name, active) values (36, 'Redhold Polytrichum Moss', false);
insert into products (product_id, product_name, active) values (37, 'Tampflex Splitleaf Cyanea', false);
insert into products (product_id, product_name, active) values (38, 'Pannier James'' Waterlily', true);
insert into products (product_id, product_name, active) values (39, 'Y-find Missouri Fontinalis Moss', true);
insert into products (product_id, product_name, active) values (40, 'Wrapsafe Barbary Fig', false);
insert into products (product_id, product_name, active) values (41, 'Treeflex Canarygrass', false);
insert into products (product_id, product_name, active) values (42, 'Biodex Island Speedwell', false);
insert into products (product_id, product_name, active) values (43, 'Bitchip Winter Creeper', true);
insert into products (product_id, product_name, active) values (44, 'Kanlam Shield Lichen', false);
insert into products (product_id, product_name, active) values (45, 'Regrant Marula', true);
insert into products (product_id, product_name, active) values (46, 'Tresom Red River Scaleseed', false);
insert into products (product_id, product_name, active) values (47, 'Wrapsafe Cleveland''s Ragwort', false);
insert into products (product_id, product_name, active) values (48, 'Greenlam Borrego Milkvetch', true);
insert into products (product_id, product_name, active) values (49, 'Subin Snow Lichen', false);
insert into products (product_id, product_name, active) values (50, 'Duobam Bigelow''s Desertgrass', true);
insert into products (product_id, product_name, active) values (51, 'Zathin Longbarb Arrowhead', false);
insert into products (product_id, product_name, active) values (52, 'Greenlam Spider Milkweed', true);
insert into products (product_id, product_name, active) values (53, 'Asoka Obtuse Sedge', false);
insert into products (product_id, product_name, active) values (54, 'Cardguard Tussock Dropseed', true);
insert into products (product_id, product_name, active) values (55, 'Konklab California Swordfern', false);
insert into products (product_id, product_name, active) values (56, 'Greenlam Comb-leaf Philodendron', true);
insert into products (product_id, product_name, active) values (57, 'Ventosanzap Curl-leaf Mountain Mahogany', true);
insert into products (product_id, product_name, active) values (58, 'Solarbreeze Wedgeleaf', false);
insert into products (product_id, product_name, active) values (59, 'Hatity Vahl''s Alkaligrass', true);
insert into products (product_id, product_name, active) values (60, 'Tempsoft Physcomitrium Moss', true);
insert into products (product_id, product_name, active) values (61, 'Konklux Pinewoods Milkweed', false);
insert into products (product_id, product_name, active) values (62, 'Daltfresh Georgia Sweetshrub', true);
insert into products (product_id, product_name, active) values (63, 'Sub-Ex Tropical Sage', true);
insert into products (product_id, product_name, active) values (64, 'Regrant Germander Meadowsweet', false);
insert into products (product_id, product_name, active) values (65, 'Sub-Ex Coville''s Rush', true);
insert into products (product_id, product_name, active) values (66, 'Stringtough Erect Pricklypear', true);
insert into products (product_id, product_name, active) values (67, 'Opela Showy Baby''s-breath', true);
insert into products (product_id, product_name, active) values (68, 'Otcom Barbados Cherry', true);
insert into products (product_id, product_name, active) values (69, 'Solarbreeze Emperor Crowngrass', false);
insert into products (product_id, product_name, active) values (70, 'Otcom Sturdy Bulrush', true);
insert into products (product_id, product_name, active) values (71, 'Redhold Beard Lichen', false);
insert into products (product_id, product_name, active) values (72, 'Voyatouch Mock Pennyroyal', true);
insert into products (product_id, product_name, active) values (73, 'Keylex Fowl Bluegrass', true);
insert into products (product_id, product_name, active) values (74, 'Sonair Cooley''s False Buttercup', false);
insert into products (product_id, product_name, active) values (75, 'Zaam-Dox Spike Lichen', false);
insert into products (product_id, product_name, active) values (76, 'Viva Wavyleaf Soap Plant', true);
insert into products (product_id, product_name, active) values (77, 'Tin Caribbean Bristlegrass', false);
insert into products (product_id, product_name, active) values (78, 'Solarbreeze Seneca Snakeroot', true);
insert into products (product_id, product_name, active) values (79, 'Vagram Wild Mustard', false);
insert into products (product_id, product_name, active) values (80, 'Zamit Drummond''s Plagiomnium Moss', true);
