DROP TABLE IF EXISTS stores CASCADE;
create table stores (
	chain_id INT,
	store_id INT,
	store_name VARCHAR(50)
);
insert into stores (chain_id, store_id, store_name) values (1, 1, '0317 Dapin Center');
insert into stores (chain_id, store_id, store_name) values (2, 2, '60 Ridge Oak Plaza');
insert into stores (chain_id, store_id, store_name) values (6, 3, '87 Pond Alley');
insert into stores (chain_id, store_id, store_name) values (5, 4, '9292 Northfield Center');
insert into stores (chain_id, store_id, store_name) values (9, 5, '9938 Springview Terrace');
insert into stores (chain_id, store_id, store_name) values (6, 6, '3638 Sachs Terrace');
insert into stores (chain_id, store_id, store_name) values (8, 7, '77345 Lien Terrace');
insert into stores (chain_id, store_id, store_name) values (8, 8, '370 Sullivan Parkway');
insert into stores (chain_id, store_id, store_name) values (5, 9, '703 Dovetail Avenue');
insert into stores (chain_id, store_id, store_name) values (5, 10, '3 Larry Drive');
insert into stores (chain_id, store_id, store_name) values (6, 11, '6 Crownhardt Street');
insert into stores (chain_id, store_id, store_name) values (8, 12, '92538 Acker Crossing');
insert into stores (chain_id, store_id, store_name) values (7, 13, '30 1st Pass');
insert into stores (chain_id, store_id, store_name) values (2, 14, '6030 Gateway Center');
insert into stores (chain_id, store_id, store_name) values (1, 15, '872 Towne Circle');
insert into stores (chain_id, store_id, store_name) values (4, 16, '2 Schlimgen Junction');
insert into stores (chain_id, store_id, store_name) values (9, 17, '5467 Arapahoe Drive');
insert into stores (chain_id, store_id, store_name) values (8, 18, '98468 Menomonie Pass');
insert into stores (chain_id, store_id, store_name) values (7, 19, '9 Schurz Crossing');
insert into stores (chain_id, store_id, store_name) values (1, 20, '08 Killdeer Parkway');
insert into stores (chain_id, store_id, store_name) values (8, 21, '95182 Green Ridge Alley');
insert into stores (chain_id, store_id, store_name) values (10, 22, '7628 Valley Edge Junction');
insert into stores (chain_id, store_id, store_name) values (3, 23, '76111 Stone Corner Lane');
insert into stores (chain_id, store_id, store_name) values (9, 24, '88343 Scoville Drive');
insert into stores (chain_id, store_id, store_name) values (4, 25, '59908 Heffernan Point');
insert into stores (chain_id, store_id, store_name) values (6, 26, '48 Kingsford Crossing');
insert into stores (chain_id, store_id, store_name) values (2, 27, '1 Delaware Street');
insert into stores (chain_id, store_id, store_name) values (9, 28, '700 Mcguire Lane');
insert into stores (chain_id, store_id, store_name) values (7, 29, '4050 Artisan Park');
insert into stores (chain_id, store_id, store_name) values (4, 30, '09324 Magdeline Way');
insert into stores (chain_id, store_id, store_name) values (4, 31, '7381 Laurel Court');
insert into stores (chain_id, store_id, store_name) values (5, 32, '3 Brown Center');
insert into stores (chain_id, store_id, store_name) values (10, 33, '048 Rutledge Center');
insert into stores (chain_id, store_id, store_name) values (1, 34, '6141 Nova Crossing');
insert into stores (chain_id, store_id, store_name) values (6, 35, '1737 Dunning Lane');
insert into stores (chain_id, store_id, store_name) values (3, 36, '19833 Graceland Center');
insert into stores (chain_id, store_id, store_name) values (1, 37, '48 Myrtle Parkway');
insert into stores (chain_id, store_id, store_name) values (6, 38, '724 Redwing Way');
insert into stores (chain_id, store_id, store_name) values (7, 39, '98 Saint Paul Hill');
insert into stores (chain_id, store_id, store_name) values (4, 40, '9596 Little Fleur Street');
insert into stores (chain_id, store_id, store_name) values (1, 41, '500 Oneill Lane');
insert into stores (chain_id, store_id, store_name) values (7, 42, '9483 Stephen Hill');
insert into stores (chain_id, store_id, store_name) values (1, 43, '32 Dovetail Junction');
insert into stores (chain_id, store_id, store_name) values (10, 44, '93794 Eagle Crest Street');
insert into stores (chain_id, store_id, store_name) values (1, 45, '3955 Montana Drive');
insert into stores (chain_id, store_id, store_name) values (4, 46, '7248 Towne Court');
insert into stores (chain_id, store_id, store_name) values (8, 47, '3 Dexter Circle');
insert into stores (chain_id, store_id, store_name) values (10, 48, '39053 Del Mar Plaza');
insert into stores (chain_id, store_id, store_name) values (7, 49, '3149 Jay Center');
insert into stores (chain_id, store_id, store_name) values (8, 50, '421 Gulseth Court');
insert into stores (chain_id, store_id, store_name) values (9, 51, '1 Hollow Ridge Way');
insert into stores (chain_id, store_id, store_name) values (6, 52, '6140 Crescent Oaks Circle');
insert into stores (chain_id, store_id, store_name) values (3, 53, '9878 Dorton Terrace');
insert into stores (chain_id, store_id, store_name) values (1, 54, '519 Dahle Road');
insert into stores (chain_id, store_id, store_name) values (3, 55, '22 Glendale Point');
insert into stores (chain_id, store_id, store_name) values (9, 56, '57 Mayer Hill');
insert into stores (chain_id, store_id, store_name) values (5, 57, '884 Golf Plaza');
insert into stores (chain_id, store_id, store_name) values (1, 58, '12 Badeau Lane');
insert into stores (chain_id, store_id, store_name) values (7, 59, '5602 Linden Street');
insert into stores (chain_id, store_id, store_name) values (10, 60, '6 David Pass');
insert into stores (chain_id, store_id, store_name) values (4, 61, '7032 Almo Avenue');
insert into stores (chain_id, store_id, store_name) values (3, 62, '7346 Derek Lane');
insert into stores (chain_id, store_id, store_name) values (2, 63, '1977 Vernon Drive');
insert into stores (chain_id, store_id, store_name) values (6, 64, '203 Sunbrook Plaza');
insert into stores (chain_id, store_id, store_name) values (8, 65, '58 Heffernan Circle');
insert into stores (chain_id, store_id, store_name) values (9, 66, '97 Veith Hill');
insert into stores (chain_id, store_id, store_name) values (7, 67, '8 Carberry Point');
insert into stores (chain_id, store_id, store_name) values (7, 68, '32444 Warner Parkway');
insert into stores (chain_id, store_id, store_name) values (5, 69, '79 Hallows Road');
insert into stores (chain_id, store_id, store_name) values (3, 70, '653 Butternut Alley');
insert into stores (chain_id, store_id, store_name) values (10, 71, '468 Mcguire Plaza');
insert into stores (chain_id, store_id, store_name) values (5, 72, '1 Marquette Park');
insert into stores (chain_id, store_id, store_name) values (3, 73, '21108 Northport Place');
insert into stores (chain_id, store_id, store_name) values (4, 74, '59833 Carberry Plaza');
insert into stores (chain_id, store_id, store_name) values (8, 75, '2762 Hanover Park');
insert into stores (chain_id, store_id, store_name) values (4, 76, '5 Del Sol Lane');
insert into stores (chain_id, store_id, store_name) values (3, 77, '15952 Waywood Point');
insert into stores (chain_id, store_id, store_name) values (8, 78, '6 Havey Center');
insert into stores (chain_id, store_id, store_name) values (5, 79, '999 Ludington Drive');
insert into stores (chain_id, store_id, store_name) values (5, 80, '55 Cottonwood Circle');
insert into stores (chain_id, store_id, store_name) values (10, 81, '06053 Prairie Rose Alley');
insert into stores (chain_id, store_id, store_name) values (10, 82, '7684 Leroy Drive');
insert into stores (chain_id, store_id, store_name) values (6, 83, '69875 Thompson Park');
insert into stores (chain_id, store_id, store_name) values (3, 84, '626 Lyons Junction');
insert into stores (chain_id, store_id, store_name) values (7, 85, '9294 Farragut Plaza');
insert into stores (chain_id, store_id, store_name) values (3, 86, '74 Hooker Street');
insert into stores (chain_id, store_id, store_name) values (8, 87, '1676 Donald Drive');
insert into stores (chain_id, store_id, store_name) values (6, 88, '18737 Miller Park');
insert into stores (chain_id, store_id, store_name) values (1, 89, '28049 Crest Line Crossing');
insert into stores (chain_id, store_id, store_name) values (2, 90, '84 Continental Drive');
insert into stores (chain_id, store_id, store_name) values (5, 91, '35917 Transport Circle');
insert into stores (chain_id, store_id, store_name) values (6, 92, '3631 Monterey Parkway');
insert into stores (chain_id, store_id, store_name) values (8, 93, '6 Manley Drive');
insert into stores (chain_id, store_id, store_name) values (6, 94, '4 Meadow Vale Pass');
insert into stores (chain_id, store_id, store_name) values (10, 95, '86983 Kinsman Road');
insert into stores (chain_id, store_id, store_name) values (10, 96, '076 Hermina Street');
insert into stores (chain_id, store_id, store_name) values (9, 97, '21 Huxley Drive');
insert into stores (chain_id, store_id, store_name) values (6, 98, '47 Grover Avenue');
insert into stores (chain_id, store_id, store_name) values (6, 99, '8724 Gerald Park');
insert into stores (chain_id, store_id, store_name) values (1, 100, '3 Kipling Trail');
insert into stores (chain_id, store_id, store_name) values (2, 101, '98 Corben Drive');
insert into stores (chain_id, store_id, store_name) values (3, 102, '3 Moulton Road');
insert into stores (chain_id, store_id, store_name) values (7, 103, '17074 Manufacturers Place');
insert into stores (chain_id, store_id, store_name) values (6, 104, '7345 Prairieview Junction');
insert into stores (chain_id, store_id, store_name) values (10, 105, '645 Sunfield Place');
insert into stores (chain_id, store_id, store_name) values (6, 106, '764 Esker Park');
insert into stores (chain_id, store_id, store_name) values (3, 107, '0 Roth Trail');
insert into stores (chain_id, store_id, store_name) values (8, 108, '13 Shasta Trail');
insert into stores (chain_id, store_id, store_name) values (6, 109, '32 Graedel Point');
insert into stores (chain_id, store_id, store_name) values (3, 110, '360 Dennis Trail');
insert into stores (chain_id, store_id, store_name) values (6, 111, '4 3rd Center');
insert into stores (chain_id, store_id, store_name) values (6, 112, '32414 Birchwood Lane');
insert into stores (chain_id, store_id, store_name) values (8, 113, '0 Westerfield Terrace');
insert into stores (chain_id, store_id, store_name) values (9, 114, '7289 Northland Avenue');
insert into stores (chain_id, store_id, store_name) values (5, 115, '83165 Arkansas Point');
insert into stores (chain_id, store_id, store_name) values (2, 116, '459 Linden Lane');
insert into stores (chain_id, store_id, store_name) values (2, 117, '28128 Columbus Junction');
insert into stores (chain_id, store_id, store_name) values (9, 118, '21204 Longview Alley');
insert into stores (chain_id, store_id, store_name) values (1, 119, '5 Bartillon Court');
insert into stores (chain_id, store_id, store_name) values (3, 120, '30290 Melody Avenue');
insert into stores (chain_id, store_id, store_name) values (4, 121, '44574 Toban Pass');
insert into stores (chain_id, store_id, store_name) values (7, 122, '7536 Bunker Hill Junction');
insert into stores (chain_id, store_id, store_name) values (2, 123, '66325 Schiller Court');
insert into stores (chain_id, store_id, store_name) values (7, 124, '480 Blackbird Drive');
insert into stores (chain_id, store_id, store_name) values (10, 125, '1 Hauk Plaza');
insert into stores (chain_id, store_id, store_name) values (9, 126, '189 Kensington Park');
insert into stores (chain_id, store_id, store_name) values (10, 127, '21 Gerald Hill');
insert into stores (chain_id, store_id, store_name) values (6, 128, '00790 Pepper Wood Street');
insert into stores (chain_id, store_id, store_name) values (3, 129, '4529 Rockefeller Court');
insert into stores (chain_id, store_id, store_name) values (8, 130, '0 Lotheville Street');
insert into stores (chain_id, store_id, store_name) values (5, 131, '1 Lunder Crossing');
insert into stores (chain_id, store_id, store_name) values (1, 132, '4936 Manley Avenue');
insert into stores (chain_id, store_id, store_name) values (4, 133, '0 Summit Pass');
insert into stores (chain_id, store_id, store_name) values (9, 134, '384 South Avenue');
insert into stores (chain_id, store_id, store_name) values (7, 135, '71020 School Center');
insert into stores (chain_id, store_id, store_name) values (5, 136, '646 Tennyson Circle');
insert into stores (chain_id, store_id, store_name) values (9, 137, '020 Shoshone Alley');
insert into stores (chain_id, store_id, store_name) values (6, 138, '84584 Barnett Drive');
insert into stores (chain_id, store_id, store_name) values (1, 139, '5751 Thackeray Parkway');
insert into stores (chain_id, store_id, store_name) values (9, 140, '4787 Lotheville Parkway');
insert into stores (chain_id, store_id, store_name) values (4, 141, '1 Lake View Trail');
insert into stores (chain_id, store_id, store_name) values (8, 142, '8 Comanche Crossing');
insert into stores (chain_id, store_id, store_name) values (5, 143, '19 Brown Alley');
insert into stores (chain_id, store_id, store_name) values (9, 144, '92521 Delaware Avenue');
insert into stores (chain_id, store_id, store_name) values (6, 145, '30818 1st Place');
insert into stores (chain_id, store_id, store_name) values (8, 146, '40330 Cody Avenue');
insert into stores (chain_id, store_id, store_name) values (1, 147, '714 Clemons Pass');
insert into stores (chain_id, store_id, store_name) values (8, 148, '66 Granby Point');
insert into stores (chain_id, store_id, store_name) values (10, 149, '7 Pawling Center');
insert into stores (chain_id, store_id, store_name) values (10, 150, '929 Lighthouse Bay Drive');
insert into stores (chain_id, store_id, store_name) values (4, 151, '6 Porter Lane');
insert into stores (chain_id, store_id, store_name) values (10, 152, '281 Westerfield Hill');
insert into stores (chain_id, store_id, store_name) values (5, 153, '4 Kings Place');
insert into stores (chain_id, store_id, store_name) values (3, 154, '67 Haas Plaza');
insert into stores (chain_id, store_id, store_name) values (4, 155, '970 Eggendart Circle');
insert into stores (chain_id, store_id, store_name) values (1, 156, '81495 Westport Park');
insert into stores (chain_id, store_id, store_name) values (2, 157, '44463 Moulton Plaza');
insert into stores (chain_id, store_id, store_name) values (1, 158, '85083 Lindbergh Terrace');
insert into stores (chain_id, store_id, store_name) values (8, 159, '9 Elka Drive');
insert into stores (chain_id, store_id, store_name) values (4, 160, '1 Badeau Court');
insert into stores (chain_id, store_id, store_name) values (1, 161, '05237 Tennessee Center');
insert into stores (chain_id, store_id, store_name) values (5, 162, '1 Sachtjen Circle');
insert into stores (chain_id, store_id, store_name) values (6, 163, '776 Alpine Way');
insert into stores (chain_id, store_id, store_name) values (4, 164, '585 West Place');
insert into stores (chain_id, store_id, store_name) values (9, 165, '75 Sundown Street');
insert into stores (chain_id, store_id, store_name) values (3, 166, '83 Randy Alley');
insert into stores (chain_id, store_id, store_name) values (6, 167, '86751 Carpenter Circle');
insert into stores (chain_id, store_id, store_name) values (7, 168, '9 Upham Avenue');
insert into stores (chain_id, store_id, store_name) values (2, 169, '26023 Crowley Trail');
insert into stores (chain_id, store_id, store_name) values (6, 170, '0 Pine View Street');
insert into stores (chain_id, store_id, store_name) values (1, 171, '0 Crownhardt Crossing');
insert into stores (chain_id, store_id, store_name) values (1, 172, '302 Boyd Center');
insert into stores (chain_id, store_id, store_name) values (3, 173, '96 Pawling Junction');
insert into stores (chain_id, store_id, store_name) values (6, 174, '41069 Pierstorff Road');
insert into stores (chain_id, store_id, store_name) values (9, 175, '09930 Morrow Park');
insert into stores (chain_id, store_id, store_name) values (1, 176, '80 Brown Terrace');
insert into stores (chain_id, store_id, store_name) values (8, 177, '9611 Southridge Road');
insert into stores (chain_id, store_id, store_name) values (7, 178, '203 Birchwood Plaza');
insert into stores (chain_id, store_id, store_name) values (10, 179, '6 Cascade Drive');
insert into stores (chain_id, store_id, store_name) values (2, 180, '73087 Dexter Alley');
insert into stores (chain_id, store_id, store_name) values (3, 181, '4922 Vermont Alley');
insert into stores (chain_id, store_id, store_name) values (9, 182, '37108 Gulseth Junction');
insert into stores (chain_id, store_id, store_name) values (1, 183, '489 Carberry Lane');
insert into stores (chain_id, store_id, store_name) values (3, 184, '99 Fremont Way');
insert into stores (chain_id, store_id, store_name) values (4, 185, '82510 Eastwood Drive');
insert into stores (chain_id, store_id, store_name) values (3, 186, '9212 Bellgrove Trail');
insert into stores (chain_id, store_id, store_name) values (1, 187, '51118 Towne Road');
insert into stores (chain_id, store_id, store_name) values (8, 188, '047 Hansons Plaza');
insert into stores (chain_id, store_id, store_name) values (9, 189, '6 Debra Parkway');
insert into stores (chain_id, store_id, store_name) values (7, 190, '444 Monterey Plaza');
insert into stores (chain_id, store_id, store_name) values (5, 191, '28 Old Gate Alley');
insert into stores (chain_id, store_id, store_name) values (2, 192, '681 Hauk Drive');
insert into stores (chain_id, store_id, store_name) values (8, 193, '5 Colorado Court');
insert into stores (chain_id, store_id, store_name) values (9, 194, '47533 Hoepker Drive');
insert into stores (chain_id, store_id, store_name) values (5, 195, '54 Pawling Drive');
insert into stores (chain_id, store_id, store_name) values (4, 196, '525 Michigan Parkway');
insert into stores (chain_id, store_id, store_name) values (8, 197, '8 Redwing Center');
insert into stores (chain_id, store_id, store_name) values (3, 198, '69722 Shoshone Lane');
insert into stores (chain_id, store_id, store_name) values (9, 199, '292 Tennessee Way');
insert into stores (chain_id, store_id, store_name) values (5, 200, '75 Victoria Alley');
insert into stores (chain_id, store_id, store_name) values (8, 201, '474 Dennis Park');
insert into stores (chain_id, store_id, store_name) values (8, 202, '2982 Hermina Hill');
insert into stores (chain_id, store_id, store_name) values (3, 203, '42495 Prentice Plaza');
insert into stores (chain_id, store_id, store_name) values (5, 204, '1782 Montana Way');
insert into stores (chain_id, store_id, store_name) values (5, 205, '7 Rockefeller Place');
insert into stores (chain_id, store_id, store_name) values (8, 206, '729 Arkansas Plaza');
insert into stores (chain_id, store_id, store_name) values (6, 207, '484 Summerview Point');
insert into stores (chain_id, store_id, store_name) values (2, 208, '0 Coolidge Point');
insert into stores (chain_id, store_id, store_name) values (1, 209, '013 Commercial Court');
insert into stores (chain_id, store_id, store_name) values (3, 210, '3304 Morning Street');
insert into stores (chain_id, store_id, store_name) values (2, 211, '22 Parkside Junction');
insert into stores (chain_id, store_id, store_name) values (4, 212, '98605 East Park');
insert into stores (chain_id, store_id, store_name) values (3, 213, '271 Ohio Pass');
insert into stores (chain_id, store_id, store_name) values (9, 214, '70673 Buena Vista Junction');
insert into stores (chain_id, store_id, store_name) values (4, 215, '5619 Eagan Alley');
insert into stores (chain_id, store_id, store_name) values (7, 216, '6 Walton Parkway');
insert into stores (chain_id, store_id, store_name) values (4, 217, '847 David Drive');
insert into stores (chain_id, store_id, store_name) values (3, 218, '9202 Old Gate Trail');
insert into stores (chain_id, store_id, store_name) values (4, 219, '15 Steensland Drive');
insert into stores (chain_id, store_id, store_name) values (3, 220, '6815 Pearson Alley');
insert into stores (chain_id, store_id, store_name) values (10, 221, '5 Florence Street');
insert into stores (chain_id, store_id, store_name) values (9, 222, '37892 Springs Avenue');
insert into stores (chain_id, store_id, store_name) values (5, 223, '94715 Erie Point');
insert into stores (chain_id, store_id, store_name) values (9, 224, '8662 Old Shore Crossing');
insert into stores (chain_id, store_id, store_name) values (6, 225, '3 Shasta Trail');
insert into stores (chain_id, store_id, store_name) values (3, 226, '6 Pond Center');
insert into stores (chain_id, store_id, store_name) values (2, 227, '0 Troy Plaza');
insert into stores (chain_id, store_id, store_name) values (6, 228, '8614 Doe Crossing Center');
insert into stores (chain_id, store_id, store_name) values (7, 229, '8 Oak Valley Street');
insert into stores (chain_id, store_id, store_name) values (2, 230, '02625 Anniversary Pass');
insert into stores (chain_id, store_id, store_name) values (6, 231, '876 Delaware Pass');
insert into stores (chain_id, store_id, store_name) values (7, 232, '52307 Prentice Avenue');
insert into stores (chain_id, store_id, store_name) values (9, 233, '44 Pawling Crossing');
insert into stores (chain_id, store_id, store_name) values (5, 234, '9 Graceland Drive');
insert into stores (chain_id, store_id, store_name) values (5, 235, '3 Kennedy Point');
insert into stores (chain_id, store_id, store_name) values (7, 236, '773 Mifflin Crossing');
insert into stores (chain_id, store_id, store_name) values (4, 237, '033 Blaine Hill');
insert into stores (chain_id, store_id, store_name) values (10, 238, '56221 Elka Junction');
insert into stores (chain_id, store_id, store_name) values (3, 239, '9366 Southridge Junction');
insert into stores (chain_id, store_id, store_name) values (3, 240, '03208 Longview Point');
insert into stores (chain_id, store_id, store_name) values (1, 241, '37868 Basil Avenue');
insert into stores (chain_id, store_id, store_name) values (3, 242, '92987 Eliot Park');
insert into stores (chain_id, store_id, store_name) values (1, 243, '86 Hayes Court');
insert into stores (chain_id, store_id, store_name) values (8, 244, '55 Walton Court');
insert into stores (chain_id, store_id, store_name) values (5, 245, '3360 Coolidge Drive');
insert into stores (chain_id, store_id, store_name) values (8, 246, '464 Esker Place');
insert into stores (chain_id, store_id, store_name) values (9, 247, '9858 Mesta Avenue');
insert into stores (chain_id, store_id, store_name) values (5, 248, '14 Cody Way');
insert into stores (chain_id, store_id, store_name) values (2, 249, '754 Manley Point');
insert into stores (chain_id, store_id, store_name) values (1, 250, '93426 Old Gate Junction');
insert into stores (chain_id, store_id, store_name) values (8, 251, '18 Sloan Crossing');
insert into stores (chain_id, store_id, store_name) values (9, 252, '939 Express Park');
insert into stores (chain_id, store_id, store_name) values (4, 253, '928 Columbus Junction');
insert into stores (chain_id, store_id, store_name) values (1, 254, '39747 Little Fleur Road');
insert into stores (chain_id, store_id, store_name) values (2, 255, '9848 Riverside Terrace');
insert into stores (chain_id, store_id, store_name) values (6, 256, '146 Hudson Center');
insert into stores (chain_id, store_id, store_name) values (1, 257, '674 6th Place');
insert into stores (chain_id, store_id, store_name) values (5, 258, '92445 Transport Place');
insert into stores (chain_id, store_id, store_name) values (2, 259, '20566 Mccormick Trail');
insert into stores (chain_id, store_id, store_name) values (1, 260, '16509 Fallview Drive');
insert into stores (chain_id, store_id, store_name) values (4, 261, '3557 Vernon Circle');
insert into stores (chain_id, store_id, store_name) values (1, 262, '481 Vermont Road');
insert into stores (chain_id, store_id, store_name) values (10, 263, '6535 Cottonwood Place');
insert into stores (chain_id, store_id, store_name) values (4, 264, '376 Lyons Parkway');
insert into stores (chain_id, store_id, store_name) values (7, 265, '15985 Westridge Trail');
insert into stores (chain_id, store_id, store_name) values (8, 266, '91936 Havey Trail');
insert into stores (chain_id, store_id, store_name) values (9, 267, '87911 Stoughton Place');
insert into stores (chain_id, store_id, store_name) values (8, 268, '9221 Westport Plaza');
insert into stores (chain_id, store_id, store_name) values (6, 269, '6345 Vahlen Road');
insert into stores (chain_id, store_id, store_name) values (2, 270, '633 Montana Drive');
insert into stores (chain_id, store_id, store_name) values (1, 271, '7127 Everett Park');
insert into stores (chain_id, store_id, store_name) values (8, 272, '9 Swallow Way');
insert into stores (chain_id, store_id, store_name) values (9, 273, '8 7th Lane');
insert into stores (chain_id, store_id, store_name) values (6, 274, '77528 Shoshone Center');
insert into stores (chain_id, store_id, store_name) values (10, 275, '9279 Thackeray Park');
insert into stores (chain_id, store_id, store_name) values (3, 276, '017 Nancy Center');
insert into stores (chain_id, store_id, store_name) values (6, 277, '01110 Elgar Place');
insert into stores (chain_id, store_id, store_name) values (4, 278, '761 Hayes Road');
insert into stores (chain_id, store_id, store_name) values (7, 279, '699 Merrick Street');
insert into stores (chain_id, store_id, store_name) values (8, 280, '67274 Waubesa Alley');
insert into stores (chain_id, store_id, store_name) values (10, 281, '9 Burrows Lane');
insert into stores (chain_id, store_id, store_name) values (4, 282, '9790 Mendota Court');
insert into stores (chain_id, store_id, store_name) values (4, 283, '239 Pond Park');
insert into stores (chain_id, store_id, store_name) values (8, 284, '5 North Terrace');
insert into stores (chain_id, store_id, store_name) values (6, 285, '356 Pine View Court');
insert into stores (chain_id, store_id, store_name) values (4, 286, '7561 Meadow Ridge Lane');
insert into stores (chain_id, store_id, store_name) values (6, 287, '240 Messerschmidt Hill');
insert into stores (chain_id, store_id, store_name) values (6, 288, '5 Union Avenue');
insert into stores (chain_id, store_id, store_name) values (2, 289, '0108 Packers Parkway');
insert into stores (chain_id, store_id, store_name) values (4, 290, '62 Rusk Pass');
insert into stores (chain_id, store_id, store_name) values (3, 291, '0 Weeping Birch Lane');
insert into stores (chain_id, store_id, store_name) values (7, 292, '07 Morningstar Lane');
insert into stores (chain_id, store_id, store_name) values (1, 293, '623 Steensland Drive');
insert into stores (chain_id, store_id, store_name) values (4, 294, '2 Fuller Parkway');
insert into stores (chain_id, store_id, store_name) values (3, 295, '7617 Waubesa Road');
insert into stores (chain_id, store_id, store_name) values (6, 296, '28 Vidon Street');
insert into stores (chain_id, store_id, store_name) values (8, 297, '69 Nelson Place');
insert into stores (chain_id, store_id, store_name) values (9, 298, '653 Merrick Avenue');
insert into stores (chain_id, store_id, store_name) values (4, 299, '73833 Anzinger Plaza');
insert into stores (chain_id, store_id, store_name) values (8, 300, '02628 Vidon Circle');
insert into stores (chain_id, store_id, store_name) values (3, 301, '858 Crownhardt Pass');
insert into stores (chain_id, store_id, store_name) values (5, 302, '406 Ryan Parkway');
insert into stores (chain_id, store_id, store_name) values (4, 303, '0 Melrose Alley');
insert into stores (chain_id, store_id, store_name) values (2, 304, '078 Elka Street');
insert into stores (chain_id, store_id, store_name) values (2, 305, '63 Kingsford Street');
insert into stores (chain_id, store_id, store_name) values (1, 306, '612 Jackson Park');
insert into stores (chain_id, store_id, store_name) values (1, 307, '40 Service Crossing');
insert into stores (chain_id, store_id, store_name) values (8, 308, '127 Service Place');
insert into stores (chain_id, store_id, store_name) values (10, 309, '1059 Rigney Trail');
insert into stores (chain_id, store_id, store_name) values (6, 310, '78 Carioca Plaza');
insert into stores (chain_id, store_id, store_name) values (4, 311, '339 Stone Corner Road');
insert into stores (chain_id, store_id, store_name) values (10, 312, '5 Clove Hill');
insert into stores (chain_id, store_id, store_name) values (2, 313, '098 Oxford Circle');
insert into stores (chain_id, store_id, store_name) values (5, 314, '975 Cottonwood Terrace');
insert into stores (chain_id, store_id, store_name) values (8, 315, '313 Loeprich Parkway');
insert into stores (chain_id, store_id, store_name) values (2, 316, '9014 Summer Ridge Point');
insert into stores (chain_id, store_id, store_name) values (4, 317, '90959 Haas Drive');
insert into stores (chain_id, store_id, store_name) values (8, 318, '3100 Pawling Lane');
insert into stores (chain_id, store_id, store_name) values (10, 319, '0 Atwood Avenue');
insert into stores (chain_id, store_id, store_name) values (1, 320, '0 Lakewood Gardens Center');
insert into stores (chain_id, store_id, store_name) values (2, 321, '12 Pierstorff Trail');
insert into stores (chain_id, store_id, store_name) values (7, 322, '368 Shelley Street');
insert into stores (chain_id, store_id, store_name) values (8, 323, '7955 Delladonna Center');
insert into stores (chain_id, store_id, store_name) values (3, 324, '1 5th Plaza');
insert into stores (chain_id, store_id, store_name) values (2, 325, '23 Lakewood Drive');
insert into stores (chain_id, store_id, store_name) values (7, 326, '9913 Nobel Plaza');
insert into stores (chain_id, store_id, store_name) values (2, 327, '65309 Nevada Parkway');
insert into stores (chain_id, store_id, store_name) values (1, 328, '5177 Spenser Place');
insert into stores (chain_id, store_id, store_name) values (7, 329, '941 Towne Crossing');
insert into stores (chain_id, store_id, store_name) values (7, 330, '599 Memorial Center');
insert into stores (chain_id, store_id, store_name) values (1, 331, '843 Valley Edge Pass');
insert into stores (chain_id, store_id, store_name) values (2, 332, '93 Bartillon Park');
insert into stores (chain_id, store_id, store_name) values (4, 333, '5 Schmedeman Terrace');
insert into stores (chain_id, store_id, store_name) values (5, 334, '84 Warrior Alley');
insert into stores (chain_id, store_id, store_name) values (2, 335, '88 Florence Avenue');
insert into stores (chain_id, store_id, store_name) values (5, 336, '7 Delladonna Road');
insert into stores (chain_id, store_id, store_name) values (10, 337, '6 Melrose Avenue');
insert into stores (chain_id, store_id, store_name) values (10, 338, '89 Westridge Alley');
insert into stores (chain_id, store_id, store_name) values (2, 339, '850 Maywood Circle');
insert into stores (chain_id, store_id, store_name) values (6, 340, '27 Menomonie Hill');
insert into stores (chain_id, store_id, store_name) values (8, 341, '12 Washington Center');
insert into stores (chain_id, store_id, store_name) values (3, 342, '21165 Dennis Road');
insert into stores (chain_id, store_id, store_name) values (9, 343, '259 Village Green Alley');
insert into stores (chain_id, store_id, store_name) values (5, 344, '8 Canary Way');
insert into stores (chain_id, store_id, store_name) values (4, 345, '06501 Roxbury Court');
insert into stores (chain_id, store_id, store_name) values (9, 346, '308 Carberry Circle');
insert into stores (chain_id, store_id, store_name) values (10, 347, '7201 Scoville Pass');
insert into stores (chain_id, store_id, store_name) values (6, 348, '6 Jay Road');
insert into stores (chain_id, store_id, store_name) values (5, 349, '38269 Morrow Junction');
insert into stores (chain_id, store_id, store_name) values (2, 350, '5220 Kings Road');
insert into stores (chain_id, store_id, store_name) values (4, 351, '49 Rusk Road');
insert into stores (chain_id, store_id, store_name) values (4, 352, '99161 Forest Run Way');
insert into stores (chain_id, store_id, store_name) values (5, 353, '9521 Mcbride Point');
insert into stores (chain_id, store_id, store_name) values (2, 354, '72 Grasskamp Trail');
insert into stores (chain_id, store_id, store_name) values (8, 355, '440 Grim Hill');
insert into stores (chain_id, store_id, store_name) values (4, 356, '6 Quincy Terrace');
insert into stores (chain_id, store_id, store_name) values (7, 357, '624 Chive Avenue');
insert into stores (chain_id, store_id, store_name) values (1, 358, '01106 High Crossing Hill');
insert into stores (chain_id, store_id, store_name) values (4, 359, '0 Fulton Place');
insert into stores (chain_id, store_id, store_name) values (6, 360, '0317 Pankratz Hill');
insert into stores (chain_id, store_id, store_name) values (4, 361, '589 Fairview Street');
insert into stores (chain_id, store_id, store_name) values (7, 362, '754 Crownhardt Drive');
insert into stores (chain_id, store_id, store_name) values (2, 363, '230 Fairview Road');
insert into stores (chain_id, store_id, store_name) values (3, 364, '8845 Fisk Point');
insert into stores (chain_id, store_id, store_name) values (10, 365, '8 Merry Circle');
insert into stores (chain_id, store_id, store_name) values (5, 366, '04 Pennsylvania Parkway');
insert into stores (chain_id, store_id, store_name) values (8, 367, '0 Annamark Road');
insert into stores (chain_id, store_id, store_name) values (2, 368, '614 Walton Point');
insert into stores (chain_id, store_id, store_name) values (3, 369, '9748 Huxley Way');
insert into stores (chain_id, store_id, store_name) values (8, 370, '4420 Roth Parkway');
insert into stores (chain_id, store_id, store_name) values (7, 371, '2 Kedzie Hill');
insert into stores (chain_id, store_id, store_name) values (10, 372, '31625 Claremont Junction');
insert into stores (chain_id, store_id, store_name) values (8, 373, '5879 Tomscot Center');
insert into stores (chain_id, store_id, store_name) values (5, 374, '397 Butterfield Place');
insert into stores (chain_id, store_id, store_name) values (1, 375, '32658 Fieldstone Hill');
insert into stores (chain_id, store_id, store_name) values (4, 376, '1 Starling Terrace');
insert into stores (chain_id, store_id, store_name) values (1, 377, '9045 Gerald Place');
insert into stores (chain_id, store_id, store_name) values (9, 378, '1893 Grasskamp Terrace');
insert into stores (chain_id, store_id, store_name) values (7, 379, '57809 Cordelia Plaza');
insert into stores (chain_id, store_id, store_name) values (6, 380, '82451 Toban Lane');
insert into stores (chain_id, store_id, store_name) values (1, 381, '642 Kipling Pass');
insert into stores (chain_id, store_id, store_name) values (7, 382, '8 Ridge Oak Circle');
insert into stores (chain_id, store_id, store_name) values (3, 383, '89183 Westerfield Way');
insert into stores (chain_id, store_id, store_name) values (3, 384, '9784 Michigan Pass');
insert into stores (chain_id, store_id, store_name) values (7, 385, '304 4th Way');
insert into stores (chain_id, store_id, store_name) values (10, 386, '2963 Mockingbird Crossing');
insert into stores (chain_id, store_id, store_name) values (8, 387, '9 Moose Terrace');
insert into stores (chain_id, store_id, store_name) values (10, 388, '3672 Elgar Court');
insert into stores (chain_id, store_id, store_name) values (7, 389, '87712 Straubel Street');
insert into stores (chain_id, store_id, store_name) values (1, 390, '15930 Maple Wood Place');
insert into stores (chain_id, store_id, store_name) values (7, 391, '61 Red Cloud Lane');
insert into stores (chain_id, store_id, store_name) values (6, 392, '740 Ridge Oak Circle');
insert into stores (chain_id, store_id, store_name) values (9, 393, '2 Buena Vista Center');
insert into stores (chain_id, store_id, store_name) values (5, 394, '8573 Karstens Road');
insert into stores (chain_id, store_id, store_name) values (9, 395, '4 Anderson Center');
insert into stores (chain_id, store_id, store_name) values (10, 396, '29864 Bultman Way');
insert into stores (chain_id, store_id, store_name) values (1, 397, '573 Green Center');
insert into stores (chain_id, store_id, store_name) values (9, 398, '8315 Merry Place');
insert into stores (chain_id, store_id, store_name) values (10, 399, '9 Lerdahl Parkway');
insert into stores (chain_id, store_id, store_name) values (10, 400, '935 Onsgard Trail');
